### ISSUE TITLE
Modal contents exceed modal width

### ISSUE THREAD

**Issue by mikeerickson** [kouts/vue-modal#10]
What would cause this UI artifact?  It is a pretty simple dialog so far as I can gather.  I have tried adjusting various classes, etc. which are exposed as props, but nothing helps

![image](https://user-images.githubusercontent.com/183153/97624889-f941a980-19e4-11eb-98ac-9edb715b3b4a.png)

**Comment by kouts** [comment]
Maybe try setting the `modalClass` to a class with `max-width` e.g 800px, you can also achieve the same result with `modalStyle`

**Comment by mikeerickson** [comment]
Ya, I tried using `width` but not `max-width` in both of these props.  I will give it a whirl
