### ISSUE TITLE
Defining z-index (assuming)

### ISSUE THREAD

**Issue by mikeerickson** [kouts/vue-modal#17]
Hello

I am using this project for many of our application modals and all is working great (thank you)

I have run into a situation where I need to show a modal on top of another, but when the second dialog is displayed, it is actually "under" (see screenshot) the previous dialog and cant seem to figure out where to address the issue

I am assuming it can be solved with `z-index` (I am not very keen with CSS).  

Do you have any advise as to where I could set the `z-index` of the second modal so it is always on top of the other modal dialogs.

![image](https://user-images.githubusercontent.com/183153/112348978-90a1e480-8c85-11eb-869f-4093f149b8cd.png)

**Comment by kouts** [comment]
Hello @mikeerickson , can you try setting the base-zindex prop to  a high number like e.g `:base-zindex="2050"`
That way you should be able to display the `vue-modal` on top of the other modal.

**Comment by mikeerickson** [comment]
Hello @kouts 

Yes indeed, this fixed the issue!  Thanks for the quick response, I apologize for missing this in the documentation.
