### ISSUE TITLE
Dialog window size?

### ISSUE THREAD

**Issue by mikeerickson** [kouts/vue-modal#18]
Hello

How would I go about setting the width and height of the dialog?

All seems to be working as I would expect, but the actual size of the dialog is pretty big (mostly the width).

How would one go about controlling the width?

**Comment by kouts** [comment]
`vue-modal` has its default `max-width` set to `500px`
There are two ways that you can customize that:
- Using the `modal-style` prop e.g `:modal-style="{ 'max-width': '200px' }"`
- Using the `modal-class` prop e.g `modal-class="my-custom-class"`
and then in your styles
```
  .my-custom-class {
    max-width: 200px;
  }
```

**Comment by mikeerickson** [comment]
Fantastic, thank you very much!  All my dialog needs for today are working perfectly!
