### ISSUE TITLE
n.default.extend

### ISSUE THREAD

**Issue by barysh** [kouts/vue-modal#29]
Uncaught TypeError: n.default.extend is not a function.

I'am using Vue 3.

**Comment by kouts** [comment]
Hey @barysh, vue-modal currently works with Vue.js 2.
I'll leave this issue open so that if there's enough interest I can start working on a version that supports Vue.js 3.

**Comment by barysh** [comment]
Ok, thanks!

**Comment by kouts** [comment]
Closing this since `vue-modal` now supports Vue.js 3.
