### ISSUE TITLE
remove autofocus

### ISSUE THREAD

**Issue by amchconsult** [kouts/vue-modal#40]
Hi,
How can I remove the autofocus or a selector to enable/disable?

afterOpen()
// this.handleFocus(this.$refs['vm-wrapper'])

Also, is it a way to create a modal from javascript like awesome-notifications library?

thank you

**Comment by kouts** [comment]
Hi @amchconsult, there's no option to remove autofocus ATM.
What you can do though is try setting the `autofocus` attribute to a non-visible element inside the modal.

Also there's no option to create a modal programmatically.

**Comment by amchconsult** [comment]
thank you
