### ISSUE TITLE
Disable click outside

### ISSUE THREAD

**Issue by mikeerickson** [kouts/vue-modal#9]
Hello

I have just stumbled upon your component and am curious if a prop exists to prevent the closing of dialog when clicking outside the window?   I don't see a prop for this, thus reason for asking?

Does the `enableClose` control this by chance?

**Comment by kouts** [comment]
Hello @mikeerickson, yes,  setting `enableClose` to `false` will prevent the closing of dialog.

**Comment by mikeerickson** [comment]
Works like a charm :-)
